% I don't know how to do methods in matlab
% objects
function [feature] = get_feature(comp)
    feature = [...
                comp.height ...
                comp.width ...
                comp.prop_height ...
                comp.prop_width ...
                comp.swt_mean ...
                comp.swt_var ...
                comp.gray_err ...
                comp.morphed_num_pxl ...
                ];
end
